### ISSUE TITLE
Error in h5checktype(). H5Identifier not valid.

### ISSUE THREAD

**Issue by TomVuod** [grimbough/rhdf5#139] opened 2024-02-08 17:43 UTC
Hello, I have the following error from rhdf5 version 2.47.3 when a single-column data frame is written to the h5 file:
```
rhdf5::h5errorHandling(type = "verbose")
df <- data.frame(a=1:10)
file = tempfile()
rhdf5::h5createFile(file)
rhdf5::h5write(
    obj = df,
    file = file,
    name = "df")

res <- rhdf5::h5read(file, "df")

Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  libhdf5
    error #000: H5Tfields.c in H5T__get_member_name(): line 175
        class: HDF5
        major: Invalid arguments to routine
        minor: Bad value
    error #001: H5Tfields.c in H5Tget_member_name(): line 138
        class: HDF5
        major: Invalid arguments to routine
        minor: Inappropriate type
Error: Error in h5checktype(). H5Identifier not valid.
```
If second column is added there is no error.

**Comment by grimbough** [comment] 2024-02-08 21:28
Thanks for the report and reproducible example.  I think this must be a regression I inadvertently caused when trying to add support for complex numbers.  I'll take a look at what's happened and try to find a fix.

**Comment by grimbough** [comment] 2024-02-08 22:06
This was a logic fail, where I was trying to check the name of the second column in a compound dataset, even if there was only one column actually present.  It should be fixed in version 2.47.4

**Comment by TomVuod** [comment] 2024-02-09 07:05
Thank you for investigating it. I will be waiting for the new version because this issue generates a build error in our package submitted to Bioconductor.

**Comment by grimbough** [comment] 2024-02-23 13:31
I presume this has now propagated and the issue is resolved.  Please re-open if that's not the case.

**Closed as completed by grimbough** 2024-02-23 13:31 UTC
